### PR TITLE
Correcting the Javadoc for BaseUnit(String symbol)

### PR DESCRIPTION
**Pull request by filipvanlaenen**
This change is [Reviewable](https://reviewable.io/reviews/unitsofmeasurement/uom-se/189)

### CODE REVIEW

**Comment by keilw** [comment]
@filipvanlaenen Thanks a lot, we can do this here without problem. If we wanted to merge this into the new RI Indriya (or you would like to do this yourself) it would be great if you considered joining the JCP as an Associate Member. We'd be happy to have you as contributor on https://jcp.org/en/jsr/detail?id=385 (@natoscott did this for JSR 363 and was listed contributor on behalf of Red Hat then, too)

**Comment by keilw** [comment]
Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unitsofmeasurement/uom-se/189)*

**Comment by filipvanlaenen** [comment]
I think I did something wrong. The two unit test classes shouldn't have gone to the same pull request.

**Comment by keilw** [comment]
Not sure, if this was done by Reviewable automatically?

**Comment by keilw** [comment]
I'm packaging uom-se 1.0.9 now. Fixing a critical bug in DecimalQuantity and other issues mostly based on Indriya. @filipvanlaenen Would you raise PRs similar to the relevant ones here also for Indriya?

**Pull request merged**
