### PR TITLE
Unix line endings

### PR DESCRIPTION
**Pull request by Pr0methean**
Required so that Unix users can edit files without the entire tree being marked changed in a pull request that also contains real changes.

### CODE REVIEW

**Comment by Pr0methean** [comment]
Closing since I found out about git config core.autocrlf

**Comment by garretwilson** [comment]
The newer and better approach is `.gitattributes`. The old `core.autocrlf` approach requires that the user configure their client correctly (as you're seeing). You should read http://adaptivepatchwork.com/2012/03/01/mind-the-end-of-your-line/ .

I'm pretty sure @magnonasc went through and added a `.gitattributes` to https://github.com/unitsofmeasurement/uom-systems as part of https://github.com/unitsofmeasurement/uom-systems/issues/66 . I recommend you do the same for the other repositories.

**Comment by Pr0methean** [comment]
Reopening since the .gitattributes change has already been done, but apparently isn't retroactive or something.

**Comment by keilw** [comment]
This is an awful lot of files affected. I'm afraid, because many downstream projects (e.g. Eclipse SmartHome, see https://github.com/eclipse/smarthome/blob/master/targetplatform/smarthome.target) now rely on uom-se, we can only accept such PR if you're willing to sign the ECA: https://www.eclipse.org/legal/ECA.php

I talked to @garretwilson and @magnonasc about it, but their contribution (aside from a file or two here, it's primarily tests) are so far restricted to https://github.com/unitsofmeasurement/uom-systems, especially the UCUM system. Which as such is not used by Eclipse projects. UOM-SE is, so before having someone mentioned to have touched Ten Thousands lines of codes (even if it's just a linefeed setting) we must ensure, this project is not banned by Eclipse like the RI (for different reasons and given the low installation base of Java ME 8 Embedded, we can live with that for now)

Thanks,
Werner

**Comment by magnonasc** [comment]
Yes, it happens when you set the line endings after a lot of people using different operational systems change the files. To avoid things like this the `.gitattributes` must be your template, it should be one of the first files added, so you'll never have a problem like this.

A `.gitattributes` must be added to this project as we've done with `uom-systems`, but don't forget to set the line endings into a single one, when I changed it on `uom-se` it has half of its files using LF and other using CRLF, so I had to convert them into the same one (CRLF) and add the `.gitattributes` so it may not be affected again.

**Comment by keilw** [comment]
I don't think GitHub does it by default when you create a new repo, does it?

**Comment by magnonasc** [comment]
I'm not sure about that, I don't work that much with GitHub, I use mostly Bitbucket, but I don't think so.
Tell me if you find such feature here, it would be really useful.

**Comment by Pr0methean** [comment]
I've now signed the ECA: https://accounts.eclipse.org/user/39818/eca

**Comment by keilw** [comment]
Thanks a lot. You work for Google:-) Do you also use JSR 363 there somewhere? Google is not in the JCP EC any more, but we received constructive input by Josh Bloch earlier and more recently Mark Davis.

**Comment by Pr0methean** [comment]
I left Google before we deployed Java 8.

**Comment by keilw** [comment]
I did merge it. After a full build in Eclipse I was asked to push all 125 files again. Hope that did not undo anything, but as @garretwilson suggested, I added a .gitattributes file similar to those in uom-system, now it seems OK. If there is still a problem, please raise, otherwise I guess it should be OK now.

**Pull request merged**
