### PR TITLE
#150: Deleted entry on resource localized for pt

### PR DESCRIPTION
**Pull request by magnonasc**
I have to say that this was the funniest bug I found on these projects, I spent a lot of times looking for something wrong on my face, I could never imagine that the problem was my locale, I thought I was getting crazy about being the only one seeing this.

### CODE REVIEW

**Comment by garretwilson** [comment]
I'm confused about the purpose of locale-specific resource files here. You say there was some locale-aware serialization and parsing functionality? I guess that would be separate from the JSR 363 `UnitFormat` functionality? I'm still a little confused:

* The `UnitFormat` implementation shouldn't be affected by locale, right? It should always give the same prefixes for the units regardless of the locale---am I understanding that correctly?
* This other locale-aware formatting function --- why did it matter if the Portuguese localization had a separate symbol for "micro"? As long as both the serialization and parsing functionality both used the same resources, then it should work, right? I'm not seeing the problem.

**Comment by magnonasc** [comment]
> The UnitFormat implementation shouldn't be affected by locale, right?
It doesn't, but there's a `LocalUnitFormatParser` that's breaking the tests when the locale is portuguese, instead of using the symbol `µ` it was using `mu`, which doesn't make sense at all, as following the pattern used on the other resources it uses:
```
tec.uom.se.unit.Units.YEAR           = y //this for the symbol
tec.uom.se.unit.Units.YEAR.1         = year //this for the localized name of the unit
```
so in fact if we want it working for pt, it should be:
```
tec.uom.se.unit.Units.MICRO           = µ
tec.uom.se.unit.Units.MICRO.1         = micro //this if we wanted a localized name of the unit
```
which would be exactly the same thing as the default resource.

**Comment by magnonasc** [comment]
Another end of line problem, I'll reopen this when I fix it.

**Comment by magnonasc** [comment]
This pull request was reopened as #151.

**Comment by keilw** [comment]
@garretwilson They are for LocalUnitFormat which allows locale-specific formatting of units, not EBNFUnitFormat which only uses a single locale.

**Pull request closed without merging**
