### PR TITLE
Make a version of Measurement that uses ComparableQuantity instead of plain Quantity for better consistency with the rest of UOM, better type safety, and closer consistency to the indtended functionality of Comparable.

### PR DESCRIPTION
**Pull request by zjuhasz**
* Added MeasurementComparableQ interface which is more specific about the type of the Quantity (ComparableQuantity instead of just Quantity).
* Moved getQuantity() to Measurement interface from AbstractMeasurement class.
* Removed final modifier from getQuantity() in AbstractMeasurement.
* Measurement no longer implements comparable, instead a MeasurementComparableQ can be returned and the Quantity it contains can be compared with others.
* Added two new overloaded static of(ComparableQuantity q) methods to Measurement that take ComparableQuantities instead of plain Quantities and return DefaultComparableQ as MeasurementComparableQ instead of Default as Measurement.
* Overrode equals(), hashCode(), and toString() in AbstractMeasurement.

### CODE REVIEW

**Comment by zjuhasz** [comment]
Another option could be to make Measurement have another generic parameter which is the type of Quantity it returns. I mostly just think there needs to be some way to safely get ComparableQuantity from a Measurement without type checking or casting when it's used and that Measurement itself should not implement Comparable because there is no good way to do this without ignoring the time at which the Measurement was taken.

**Comment by keilw** [comment]
public interface Measurement<Q extends Quantity<Q>> takes the type of quantity as in Length, Mass, etc. adding another generic argument could complicate things. We had something similar on Quantity earlier to tell the exact type of **value**, but for the sake of simplicity that was reduced to value being numeric.

The PR fails because of a missing license header, otherwise it looks OK.

**Comment by zjuhasz** [comment]
I think I added the license header correctly in new commit.

**Comment by keilw** [comment]
Had to remove the redundant interface as it makes no real sense to have more than one Measurement, but the local implementation details e.g. of() also taking a concrete ComparableQuantity work without it.
Thanks,
Werner

**Comment by zjuhasz** [comment]
Yeah, good point.

**Pull request merged**
