### PR TITLE
Enhancement: AbstractUnit's final methods now guarantee to return AbstractUnit<> instead of just Unit<>

### PR DESCRIPTION
**Pull request by Pr0methean**
Narrows the return type of final methods in AbstractUnit from Unit<> to AbstractUnit<>. The only behavioural change is that if a third-party Unit<> that doesn't extend AbstractUnit<> is passed to one of these methods for transformation, it will be wrapped in a ProductUnit even when that wasn't previously necessary. This may cause some tests that rely on reference equality to fail; but in a near-future PR, I'll fix this by refining the implementation of ProductUnit.equals().

### CODE REVIEW

**Comment by Pr0methean** [comment]
Note: Most of the deltas in this PR are in the first commit, which contains only those whitespace formatting changes that "mvn test" automatically performed.

**Comment by Pr0methean** [comment]
Closing to first separately PR the formatting update.

**Comment by keilw** [comment]
Please also consider porting some of those PRs to https://github.com/unitsofmeasurement/indriya. It is currently in "stealth mode" but supposed to be a unified RI of an upcoming new Units JSR.

**Comment by keilw** [comment]
@Pr0methean What is the main benefit or improvement of returning `AbstractUnit` instead of `Unit` by most methods in the `AbstractUnit` class? Not sure about the static `parse()` method btw. I saw it also returns `AbstractUnit`. Before applying to Indriya which will be a future RI of the next API/JSR version, we should understand what was won from this change. A possible goal of a new API could be to allow mixing implementations in the same module or class path, see https://github.com/unitsofmeasurement/unit-api/issues/38.

**Pull request merged**
