### PR TITLE
Merge

### PR DESCRIPTION
**Pull request by Pr0methean**

### CODE REVIEW

**Comment by Pr0methean** [comment]
Sorry, I thought I was using this to merge two of my own branches.

**Comment by keilw** [comment]
Ok, it seems https://github.com/unitsofmeasurement/uom-se/pull/172 was not part of that new PR. Will you raise it again?

**Comment by Pr0methean** [comment]
I will, once I can get it working. Any chance you guys can come on Gitter?

**Comment by Pr0methean** [comment]
I'm having some test failures I can't track down.

**Comment by keilw** [comment]
Please have a look at https://github.com/unitsofmeasurement/indriya/tree/master/src/main/java/tec/units/indriya/quantity/time

I forward ported relevant parts of https://github.com/unitsofmeasurement/uom-se/pull/172 into the future RI (so this is currently not on a CI till later that year) and I fixed a few issues both in the two `Quantity` types and tests. E.g. it runs into the **equivalence** challenge, where it is only safe to compare the two converters, not the result to a constant like `HERTZ`. All tests pass for Indriya.

**Comment by Pr0methean** [comment]
I've replaced the inverse() methods with Indriya's version, and I'm still getting the same errors as before. Hunting through the diffs for what else has changed (?w=1 isn't working in this case)...

**Comment by Pr0methean** [comment]
Here are the failures, in case it helps:

[ERROR]   EBNFFormatTest.testParseInverseKg:80 expected:<[1/kg]> but was:<[one]>
[ERROR]   EBNFFormatTest.testParseInverseL:86 expected:<[1/l]> but was:<[one]>
[ERROR]   EBNFFormatTest.testParseInverseM:74 expected:<[1/m]> but was:<[one]>
[ERROR]   DecimalComparableQuantityTest.divideOperationsExceptionTest Expected exception: java.lang.ClassCastException
[ERROR]   DecimalComparableQuantityTest.multiplyOperationsExceptionTest Expected exception: java.lang.ClassCastException
[ERROR]   DoubleComparableQuantityTest.divideOperationsExceptionTest Expected exception: java.lang.ClassCastException
[ERROR]   DoubleComparableQuantityTest.multiplyOperationsExceptionTest Expected exception: java.lang.ClassCastException
[ERROR]   NumberComparableQuantityTest.divideOperationsExceptionTest Expected exception: java.lang.ClassCastException
[ERROR]   NumberComparableQuantityTest.multiplyOperationsExceptionTest Expected exception: java.lang.ClassCastException

**Comment by keilw** [comment]
That's funny, I am not getting any of these with Indriya, and they are not yet so far apart.

**Comment by Pr0methean** [comment]
Ah, I see the difference, Indriya didn't have to narrow anything from Unit to AbstractUnit.

**Comment by Pr0methean** [comment]
I'll try to determine which of my narrowings are breaking the tests, and revert them.

**Comment by Pr0methean** [comment]
How do I refer to this repo's master from my fork's master? I thought it was just called "origin", but I'm trying
```
git pull origin master
git branch cptimefix 1c1c1c1d2a530b6cd4bc0194b3a7051f9e06c9f9
```
and I get `fatal: Not a valid branch point: '1c1c1c1d2a530b6cd4bc0194b3a7051f9e06c9f9'` (I may have run a few rebase and reset commands while trying to deal with the newline mess.)

**Comment by Pr0methean** [comment]
OK, it seems they're already broken in trunk. I'll open an issue.

**Comment by keilw** [comment]
It's not reproducable anywhere. Build works fine on Windows locally and the CI server running Oracle JDK 8 on an Ubuntu server, so it should be fairly close. The only thing that might be broken is OpenJDK as it looks like ;-/

**Pull request closed without merging**
